baseURL = "https://www.abailey.ca/"
title = "Aaron Bailey Counselling"
languageCode = "en-ca"
paginate = 10
enableRobotsTXT = true
copyright = "© 2025 Aaron Bailey Counselling"

[params]
  description = "Registered Clinical Counsellor in Brentwood Bay, BC offering youth and adult counselling."
  phone = "(778)-557-5504"
  email = "abaileycounselling@gmail.com"
  location = "Brentwood Bay, BC"
  og_image = "/images/office.jpg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[params.social]
  instagram = ""
  facebook = ""
  linkedin = ""

[services]
  [services.googleAnalytics]
    id = ""

[permalinks]
  page = "/:slug/"
