baseURL = "https://abaileycounselling.netlify.app/"
canonifyURLs = true
enableRobotsTXT = true
title = "Bailey’s Counselling"

[menu]
  [[menu.main]] name = "Counselling" url = "/counselling/" weight = 10
  [[menu.main]] name = "Rates & Services" url = "/rates-services/" weight = 20
  [[menu.main]] name = "Resources" url = "/resources/" weight = 30
  [[menu.main]] name = "Meet the Counsellor" url = "/meet-the-counsellor/" weight = 40
  [[menu.main]] name = "Contact" url = "/contact/" weight = 50
