[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.115.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.115.4"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.115.4"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.115.4"
